# ANN

In [12]:
import numpy as np

### Step 0: Read input and output



### input array

In [13]:
X=np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])

### Output

In [14]:
y=np.array([[1],[1],[0]])

### Sigmoid Function-activation function used to reduce the complexity of compution  while passing the input from one hideen layer to other


#### the ouput of sigmoid function ranges between the value 0 and 1 

In [15]:
def sigmoid (x):
    return 1/(1 + np.exp(-x))

### Derivative of Sigmoid Function is performed during the backpropagation for achieveing more accuracy

In [16]:
def derivatives_sigmoid(x):
    return x * (1 - x)

### Variable initialization

In [17]:
epoch=5000 #Setting training iterations
lr=0.1 #Setting learning rate-taking only some amount data for computation
inputlayer_neurons = 4 #number of features in data set
hiddenlayer_neurons = 3 #number of hidden layers neurons
output_neurons = 1 # number of output layer

### Step 1: Initialize weights and biases with random values (There are methods to initialize weights and biases but for now initialize with random values)


In [18]:
wh=np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons))
bh=np.random.uniform(size=(1,hiddenlayer_neurons))
wout=np.random.uniform(size=(hiddenlayer_neurons,output_neurons))
bout=np.random.uniform(size=(1,output_neurons))


In [19]:
for i in range(epoch):
    #Forward Propogation:
    #Step 2: Calculate hidden layer input:hidden_layer_input= matrix_dot_product(X,wh) + bh
    hidden_layer_input1=np.dot(X,wh)
    hidden_layer_input=hidden_layer_input1 + bh
    #Step 3: Perform non-linear transformation on hidden linear inputhiddenlayer_activations = sigmoid(hidden_layer_input)
    hiddenlayer_activations = sigmoid(hidden_layer_input)
    #Step 4: Perform linear and non-linear transformation of hidden layer activation at output layer 
    #output_layer_input = matrix_dot_product (hiddenlayer_activations * wout ) + boutoutput = sigmoid(output_layer_input)
    output_layer_input1=np.dot(hiddenlayer_activations,wout)
    output_layer_input= output_layer_input1+ bout
    output = sigmoid(output_layer_input)

    #Backpropagation
    #Compare the prediction with actual output 
    #Step 5: Calculate gradient of Error(E) at output layer
    #E = y-output
    E = y-output
    #Calculate the slope/gradient of hidden and output neurons
    #Step 6: Compute slope at output and hidden layer
    #Slope_output_layer= derivatives_sigmoid(output)
    #Slope_hidden_layer = derivatives_sigmoid(hiddenlayer_activations)
    slope_output_layer = derivatives_sigmoid(output)
    slope_hidden_layer = derivatives_sigmoid(hiddenlayer_activations)
    
    #compute the change factor/delta at output player
    #Step 7: Compute delta at output layer. d_output = E * slope_output_layer*lr

    d_output = E * slope_output_layer
    
    #In this step, the error will propoagate back into network which means at hidden layer.
    # For this, we will take the dot product of output layer delta with weight parameters of edges between hidden and output layer
    #Step 8: Calculate Error at hidden layer Error_at_hidden_layer = matrix_dot_product(d_output, wout.Transpose)
    Error_at_hidden_layer = d_output.dot(wout.T)
    #Compute the change factor at hidden layer
    #Step 9: Compute delta at hidden layer d_hiddenlayer = Error_at_hidden_layer * slope_hidden_layer
    d_hiddenlayer = Error_at_hidden_layer * slope_hidden_layer
    
    #update the weights at output and hidden layer.
    #Step 10: Update weight at both output and hidden layer
    #wout = wout + matrix_dot_product(hiddenlayer_activations.Transpose, d_output)*learning_rate
    #wh =  wh+ matrix_dot_product(X.Transpose,d_hiddenlayer)*learning_rate
    wout += hiddenlayer_activations.T.dot(d_output) *lr
    wh += X.T.dot(d_hiddenlayer) *lr
    #update the bias at output and hidden layer.
    bout += np.sum(d_output, axis=0,keepdims=True) *lr
    bh += np.sum(d_hiddenlayer, axis=0,keepdims=True) *lr
    
print("Input:\n" + str(X))   
print("Actual output: \n" + str(y))
print("Predicted output:")
print (output)

Input:
[[1 0 1 0]
 [1 0 1 1]
 [0 1 0 1]]
Actual output: 
[[1]
 [1]
 [0]]
Predicted output:
[[0.97854912]
 [0.96708017]
 [0.04759332]]
